"""
Centralized prompt templates and system instructions for LLM interactions.

This module contains all prompt templates, system instructions, and prompt-related
utilities used throughout the application.
"""

# System instructions for different LLM roles
SYSTEM_INSTRUCTIONS = {
    "evaluator": "You are an expert evaluator of AI responses. Provide objective, constructive evaluations.",
    "context_provider": """You are a learning assistant helping readers deepen their understanding of highlighted book passages.

Your role is to:
- Explain the key concept in 2-3 concise sentences
- Provide 2-3 concrete real-world examples or analogies
- Connect the idea to broader themes when relevant

Keep responses focused, practical, and under 200 words.

Format your response in markdown:
- **Key Concept:** [2-3 sentence explanation]
- **Examples:** [2-3 concrete real-world examples or analogies, as a bulleted list]
- **Connection:** [Optional: Broader theme links]""",
    "summarizer": "You are a skilled summarizer. Generate clear, concise summaries that capture the most important information.",
    "semantic_chunker": """You are a selective content extraction and semantic chunking assistant.
Extract only the most noteworthy parts of the main article content — key insights, good examples, and important ideas.
Ignore boilerplate (nav, sidebars, related articles, ads, comments) and skip filler or repetitive content.
Always respond with valid JSON.""",
}


def create_evaluation_prompt(original_prompt: str, llm_response: str) -> str:
    """
    Create a prompt for evaluating LLM response quality.

    Args:
        original_prompt: The original prompt that was sent to the LLM
        llm_response: The response generated by the LLM

    Returns:
        A formatted evaluation prompt string
    """
    return f"""Please evaluate the following LLM response based on the original prompt. 

Original Prompt:
{original_prompt}

LLM Response:
{llm_response}

Please evaluate this response on the following criteria:
1. Relevance: How well does the response address the prompt?
2. Accuracy: Is the information provided correct and factual?
3. Helpfulness: Does the response provide useful information?
4. Clarity: Is the response clear and well-structured?

Provide a score from 0.0 to 1.0 (where 1.0 is perfect) and a brief explanation of your evaluation.

Format your response as:
Score: [0.0-1.0]
Evaluation: [Your detailed evaluation]"""


def create_context_prompt(
    book_title: str,
    note_content: str,
    related_notes: list[str] | None = None,
) -> str:
    """
    Create a prompt for generating additional context for a note.

    Args:
        book_title: The title of the book the note is from
        note_content: The content of the note
        related_notes: Optional similar notes to use as supporting context

    Returns:
        A formatted context generation prompt string
    """
    prompt = f"""Book: "{book_title}"

Highlighted passage:
"{note_content}"
"""

    if related_notes:
        related_notes_text = "\n".join(f"- {note}" for note in related_notes)
        prompt += f"""

Related notes:
{related_notes_text}

Use the related notes to enrich the explanation without repeating them verbatim."""

    prompt += """

Explain this concept clearly and provide a practical example that makes it memorable."""
    return prompt


def create_summary_prompt(content: str) -> str:
    """
    Create a prompt for generating a concise summary of content.

    Args:
        content: The content to summarize

    Returns:
        A formatted summary prompt string
    """
    return f"""Please provide a concise 2-3 sentence summary of the following content:

{content}

Summary:"""


def create_chunk_context_prompt(
    url: str,
    url_title: str,
    chunk_content: str,
    related_chunks: list[str] | None = None,
) -> str:
    """
    Create a prompt for generating additional context for a URL chunk.

    Args:
        url: The URL of the webpage
        url_title: The title of the URL/webpage
        chunk_content: The content of the chunk
        related_chunks: Optional similar chunks to use as supporting context

    Returns:
        A formatted context generation prompt string
    """
    prompt = f"""Article: "{url_title}"
URL: {url}

Content passage:
"{chunk_content}"
"""

    if related_chunks:
        related_chunks_text = "\n".join(f"- {chunk}" for chunk in related_chunks)
        prompt += f"""

Related chunks:
{related_chunks_text}

Use the related chunks to enrich the explanation without repeating them verbatim."""

    prompt += """

Explain this concept clearly and provide a practical example that makes it memorable."""
    return prompt


def create_tweet_context_prompt(
    author_username: str,
    tweet_content: str,
    related_tweets: list[str] | None = None,
) -> str:
    """
    Create a prompt for generating additional context for a tweet.

    Args:
        author_username: The Twitter username of the tweet author
        tweet_content: The content of the tweet
        related_tweets: Optional similar tweets to use as supporting context

    Returns:
        A formatted context generation prompt string
    """
    prompt = f"""Tweet by @{author_username}:
"{tweet_content}"
"""

    if related_tweets:
        related_tweets_text = "\n".join(f"- {tweet}" for tweet in related_tweets)
        prompt += f"""

Related tweets:
{related_tweets_text}

Use the related tweets to enrich the explanation without repeating them verbatim."""

    prompt += """

Explain the key idea in this tweet clearly and provide a practical example or context that makes it memorable."""
    return prompt


def create_semantic_chunking_prompt(content: str) -> str:
    """
    Create a prompt for semantic chunking of content.

    Args:
        content: The raw content to chunk semantically

    Returns:
        A formatted semantic chunking prompt string
    """
    return f"""Extract the main article content from the following text, ignoring any navigation, sidebars, related articles, author bios, ads, or comments.

Then select and extract only the most noteworthy parts of the content. Not every paragraph or section needs to be included. Focus on:
- Key insights, arguments, or takeaways that capture the article's main theme
- Memorable examples, analogies, or case studies that illustrate important points
- Surprising facts, counterintuitive claims, or notable quotes
- Practical advice or actionable information

Skip filler, transitions, repetitive points, and sections that don't add substantive value.

Each extracted chunk should:
- Contain a complete thought, idea, or section
- Be 200-800 characters in length (target range)
- Use the exact original text verbatim — do not paraphrase, summarize, or reword

Text to process:
{content}

Respond with a JSON object in this exact format:
{{"chunks": ["chunk 1 text", "chunk 2 text", ...]}}"""
